title: Welcome to my example website!
theme: minima
author: Clare Horscroft
email: chorscroft@aol.co.uk
description: > # this means to ignore newlines until "baseurl:"
  This is my new GitHub pages site for testing GitHub pages and
  learning how to do new stuffs.

# social links
twitter_username: ClareHorscroft # DO NOT include the @ character, or else the build will fail!
github_username:  chorscroft # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
